"""drop uq_tpl_reward from template_reward_links

Revision ID: 02fa15d4c52b
Revises: 7524a4355891
Create Date: 2025-07-16 13:16:25.488848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02fa15d4c52b'
down_revision: Union[str, None] = '7524a4355891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_rewards', 'secret',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('loyalty_card_instances', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('loyalty_card_instances', 'stamps_given',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loyalty_card_instances', 'reward_claimed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_loyalty_instances_user', table_name='loyalty_card_instances')
    op.alter_column('loyalty_card_rules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('loyalty_card_rules', 'created_at')
    op.alter_column('loyalty_card_stamp_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('loyalty_card_codes_code_key', 'loyalty_card_stamp_codes', type_='unique')
    op.create_index(op.f('ix_loyalty_card_stamp_codes_code'), 'loyalty_card_stamp_codes', ['code'], unique=True)
    op.alter_column('loyalty_card_stamps', 'given_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('loyalty_card_templates', 'title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('loyalty_card_templates', 'promo_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('loyalty_card_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('loyalty_card_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_loyalty_templates_company', table_name='loyalty_card_templates')
    op.create_index(op.f('ix_loyalty_card_templates_company_id'), 'loyalty_card_templates', ['company_id'], unique=False)
    op.alter_column('reward_redemption_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tpl_reward', 'template_reward_links', ['template_id', 'reward_id'])
    op.alter_column('reward_redemption_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_loyalty_card_templates_company_id'), table_name='loyalty_card_templates')
    op.create_index('ix_loyalty_templates_company', 'loyalty_card_templates', ['company_id'], unique=False)
    op.alter_column('loyalty_card_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('loyalty_card_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('loyalty_card_templates', 'promo_text',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('loyalty_card_templates', 'title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('loyalty_card_stamps', 'given_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_loyalty_card_stamp_codes_code'), table_name='loyalty_card_stamp_codes')
    op.create_unique_constraint('loyalty_card_codes_code_key', 'loyalty_card_stamp_codes', ['code'])
    op.alter_column('loyalty_card_stamp_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('loyalty_card_rules', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('loyalty_card_rules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_loyalty_instances_user', 'loyalty_card_instances', ['user_id'], unique=False)
    op.alter_column('loyalty_card_instances', 'reward_claimed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('loyalty_card_instances', 'stamps_given',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loyalty_card_instances', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_rewards', 'secret',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###