"""add coupons

Revision ID: 0851df5ebc2c
Revises: 1f01a11f3171
Create Date: 2025-08-08 09:42:10.196392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0851df5ebc2c'
down_revision: Union[str, None] = '1f01a11f3171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('usage_limit_total', sa.Integer(), nullable=True),
    sa.Column('usage_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_location_name', sa.String(length=120), nullable=True),
    sa.Column('source_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_coupon_company_code')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=False)
    op.create_index(op.f('ix_coupons_company_id'), 'coupons', ['company_id'], unique=False)
    op.create_index(op.f('ix_coupons_source_location'), 'coupons', ['source_location'], unique=False)
    op.create_table('coupon_categories',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'category_id')
    )
    op.create_table('coupon_items',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'inventory_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_table('coupon_items')
    op.drop_table('coupon_categories')
    op.drop_index(op.f('ix_coupons_source_location'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_company_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
