"""add PIX

Revision ID: 0be390d517fb
Revises: 60088e25fd3c
Create Date: 2025-06-17 12:02:53.669079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be390d517fb'
down_revision: Union[str, None] = '60088e25fd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_payments', sa.Column('pix_copy_paste_code', sa.Text(), nullable=True))
    op.add_column('company_payments', sa.Column('pix_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('company_payments', 'pix_qr_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_payments', 'pix_qr_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('company_payments', 'pix_expires_at')
    op.drop_column('company_payments', 'pix_copy_paste_code')
    # ### end Alembic commands ###
