"""create users table

Revision ID: 1f01a11f3171
Revises: 
Create Date: 2025-08-07 14:30:11.708392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f01a11f3171'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('online_url', sa.String(length=255), nullable=True),
    sa.Column('only_online', sa.Boolean(), nullable=False),
    sa.Column('accepted_terms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.create_index(op.f('ix_companies_customer_id'), 'companies', ['customer_id'], unique=True)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_location'), 'companies', ['location'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_points'), 'milestones', ['points'], unique=False)
    op.create_table('phone_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verifications_code'), 'phone_verifications', ['code'], unique=False)
    op.create_index(op.f('ix_phone_verifications_phone'), 'phone_verifications', ['phone'], unique=False)
    op.create_table('point_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('reward_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('short_desc', sa.String(length=255), nullable=True),
    sa.Column('long_desc', sa.Text(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_reward_products_active'), 'reward_products', ['active'], unique=False)
    op.create_table('selection_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('product', 'category', name='selection_type'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'item_id', name='uq_selection_type_item')
    )
    op.create_index(op.f('ix_selection_items_item_id'), 'selection_items', ['item_id'], unique=False)
    op.create_table('slide_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_terms', sa.Boolean(), nullable=False),
    sa.Column('pre_registered', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referral_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_branches_slug'), 'branches', ['slug'], unique=False)
    op.create_table('cashback_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('max_per_user', sa.Integer(), nullable=True),
    sa.Column('min_cashback_per_user', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_programs_company_id'), 'cashback_programs', ['company_id'], unique=False)
    op.create_table('commission_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('company_categories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'category_id')
    )
    op.create_table('company_password_reset_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_password_reset_codes_code'), 'company_password_reset_codes', ['code'], unique=False)
    op.create_index(op.f('ix_company_password_reset_codes_company_id'), 'company_password_reset_codes', ['company_id'], unique=False)
    op.create_table('company_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('asaas_id', sa.String(length=255), nullable=False),
    sa.Column('pix_qr_code', sa.Text(), nullable=True),
    sa.Column('pix_copy_paste_code', sa.Text(), nullable=True),
    sa.Column('pix_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_payments_asaas_id'), 'company_payments', ['asaas_id'], unique=True)
    op.create_index(op.f('ix_company_payments_company_id'), 'company_payments', ['company_id'], unique=False)
    op.create_table('company_point_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('asaas_id', sa.String(length=255), nullable=False),
    sa.Column('pix_qr_code', sa.Text(), nullable=True),
    sa.Column('pix_copy_paste_code', sa.Text(), nullable=True),
    sa.Column('pix_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='purchasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['point_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_point_purchases_asaas_id'), 'company_point_purchases', ['asaas_id'], unique=True)
    op.create_index(op.f('ix_company_point_purchases_company_id'), 'company_point_purchases', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_point_purchases_plan_id'), 'company_point_purchases', ['plan_id'], unique=False)
    op.create_table('company_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.Boolean(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_rewards_company_id'), 'company_rewards', ['company_id'], unique=False)
    op.create_table('fee_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('setting_type', sa.Enum('cashback', 'points', 'loyalty', name='settingtypeenum'), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'setting_type', name='uq_fee_company_type')
    )
    op.create_index(op.f('ix_fee_settings_company_id'), 'fee_settings', ['company_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_company_id'), 'inventory_items', ['company_id'], unique=False)
    op.create_table('loyalty_card_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('promo_text', sa.String(length=120), nullable=True),
    sa.Column('color_primary', sa.String(length=7), nullable=True),
    sa.Column('color_bg', sa.String(length=7), nullable=True),
    sa.Column('stamp_icon_url', sa.String(length=255), nullable=True),
    sa.Column('stamp_total', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('emission_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emission_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emission_limit', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_card_templates_company_id'), 'loyalty_card_templates', ['company_id'], unique=False)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_code'), 'password_reset_codes', ['code'], unique=False)
    op.create_table('points_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Enum('value_spent', 'event', 'frequency', 'category', 'first_purchase', 'recurrence', 'digital_behavior', 'special_date', 'geolocation', 'inventory', name='rule_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_rules_company_id'), 'points_rules', ['company_id'], unique=False)
    op.create_table('points_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=0), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_wallets_company_id'), 'points_wallets', ['company_id'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_company_id'), 'product_categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=False)
    op.create_table('purchase_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_logs_company_id'), 'purchase_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_logs_user_id'), 'purchase_logs', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_referrals_user_company')
    )
    op.create_index(op.f('ix_referrals_company_id'), 'referrals', ['company_id'], unique=False)
    op.create_index(op.f('ix_referrals_user_id'), 'referrals', ['user_id'], unique=False)
    op.create_table('reward_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'refused', name='orderstatus'), nullable=False),
    sa.Column('refusal_msg', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=120), nullable=False),
    sa.Column('street', sa.String(length=120), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('neighborhood', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('complement', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_product_categories',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['reward_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['reward_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('transfer_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('key_type', sa.Enum('PHONE', 'EMAIL', 'CPF', 'CNPJ', 'RANDOM', name='pixkeytype'), nullable=False),
    sa.Column('key_value', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_methods_user_id'), 'transfer_methods', ['user_id'], unique=False)
    op.create_table('user_cashback_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_wallet')
    )
    op.create_index(op.f('ix_user_cashback_wallets_company_id'), 'user_cashback_wallets', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_cashback_wallets_user_id'), 'user_cashback_wallets', ['user_id'], unique=False)
    op.create_table('user_companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('user_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'milestone_id', name='uq_user_milestone')
    )
    op.create_table('user_points_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lifetime_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('today_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('month_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_stats_user_id'), 'user_points_stats', ['user_id'], unique=True)
    op.create_table('user_points_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_wallets_user_id'), 'user_points_wallets', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_company_id'), 'wallets', ['company_id'], unique=True)
    op.create_table('cashbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('amount_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cashback_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['cashback_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashbacks_program_id'), 'cashbacks', ['program_id'], unique=False)
    op.create_index(op.f('ix_cashbacks_user_id'), 'cashbacks', ['user_id'], unique=False)
    op.create_table('commission_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'debit', name='commissiontransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['commission_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_withdrawals',
    sa.Column('transfer_method_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='commissionwithdrawalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfer_method_id'], ['transfer_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['commission_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credits_wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='credittxtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_wallet_transactions_company_id'), 'credits_wallet_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_credits_wallet_transactions_wallet_id'), 'credits_wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('inventory_item_categories',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_item_id', 'category_id')
    )
    op.create_table('loyalty_card_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stamps_given', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['loyalty_card_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'user_id', name='uq_template_user')
    )
    op.create_table('loyalty_card_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('purchase_amount', 'visit', 'service_done', 'product_bought', 'category_bought', 'custom_event', name='ruletype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['loyalty_card_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['points_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_wallet_transactions_company_id'), 'points_wallet_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_points_wallet_transactions_wallet_id'), 'points_wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('reward_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['reward_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['reward_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_reward_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('stamp_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['company_rewards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['loyalty_card_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'stamp_no', name='uq_tpl_stamp')
    )
    op.create_table('user_points_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('award', 'redeem', 'adjustment', name='userpointstxtype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['points_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_points_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_transactions_company_id'), 'user_points_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_points_transactions_user_id'), 'user_points_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_points_transactions_wallet_id'), 'user_points_transactions', ['wallet_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'company_id'], ['user_cashback_wallets.user_id', 'user_cashback_wallets.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_card_stamp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['loyalty_card_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_card_stamp_codes_code'), 'loyalty_card_stamp_codes', ['code'], unique=True)
    op.create_table('loyalty_card_stamps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('stamp_no', sa.Integer(), nullable=False),
    sa.Column('given_by_id', sa.UUID(), nullable=True),
    sa.Column('given_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['given_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['loyalty_card_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_redemption_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['loyalty_card_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['template_reward_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemption_codes_code'), 'reward_redemption_codes', ['code'], unique=True)
    op.create_index(op.f('ix_reward_redemption_codes_instance_id'), 'reward_redemption_codes', ['instance_id'], unique=False)
    op.create_index(op.f('ix_reward_redemption_codes_link_id'), 'reward_redemption_codes', ['link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_redemption_codes_link_id'), table_name='reward_redemption_codes')
    op.drop_index(op.f('ix_reward_redemption_codes_instance_id'), table_name='reward_redemption_codes')
    op.drop_index(op.f('ix_reward_redemption_codes_code'), table_name='reward_redemption_codes')
    op.drop_table('reward_redemption_codes')
    op.drop_table('loyalty_card_stamps')
    op.drop_index(op.f('ix_loyalty_card_stamp_codes_code'), table_name='loyalty_card_stamp_codes')
    op.drop_table('loyalty_card_stamp_codes')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_user_points_transactions_wallet_id'), table_name='user_points_transactions')
    op.drop_index(op.f('ix_user_points_transactions_user_id'), table_name='user_points_transactions')
    op.drop_index(op.f('ix_user_points_transactions_company_id'), table_name='user_points_transactions')
    op.drop_table('user_points_transactions')
    op.drop_table('template_reward_links')
    op.drop_table('reward_order_items')
    op.drop_index(op.f('ix_points_wallet_transactions_wallet_id'), table_name='points_wallet_transactions')
    op.drop_index(op.f('ix_points_wallet_transactions_company_id'), table_name='points_wallet_transactions')
    op.drop_table('points_wallet_transactions')
    op.drop_table('loyalty_card_rules')
    op.drop_table('loyalty_card_instances')
    op.drop_table('inventory_item_categories')
    op.drop_index(op.f('ix_credits_wallet_transactions_wallet_id'), table_name='credits_wallet_transactions')
    op.drop_index(op.f('ix_credits_wallet_transactions_company_id'), table_name='credits_wallet_transactions')
    op.drop_table('credits_wallet_transactions')
    op.drop_table('commission_withdrawals')
    op.drop_table('commission_transactions')
    op.drop_index(op.f('ix_cashbacks_user_id'), table_name='cashbacks')
    op.drop_index(op.f('ix_cashbacks_program_id'), table_name='cashbacks')
    op.drop_table('cashbacks')
    op.drop_index(op.f('ix_wallets_company_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_points_wallets_user_id'), table_name='user_points_wallets')
    op.drop_table('user_points_wallets')
    op.drop_index(op.f('ix_user_points_stats_user_id'), table_name='user_points_stats')
    op.drop_table('user_points_stats')
    op.drop_table('user_milestones')
    op.drop_table('user_companies')
    op.drop_index(op.f('ix_user_cashback_wallets_user_id'), table_name='user_cashback_wallets')
    op.drop_index(op.f('ix_user_cashback_wallets_company_id'), table_name='user_cashback_wallets')
    op.drop_table('user_cashback_wallets')
    op.drop_index(op.f('ix_transfer_methods_user_id'), table_name='transfer_methods')
    op.drop_table('transfer_methods')
    op.drop_table('reward_product_categories')
    op.drop_table('reward_orders')
    op.drop_index(op.f('ix_referrals_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_company_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_purchase_logs_user_id'), table_name='purchase_logs')
    op.drop_index(op.f('ix_purchase_logs_company_id'), table_name='purchase_logs')
    op.drop_table('purchase_logs')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_company_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_points_wallets_company_id'), table_name='points_wallets')
    op.drop_table('points_wallets')
    op.drop_index(op.f('ix_points_rules_company_id'), table_name='points_rules')
    op.drop_table('points_rules')
    op.drop_index(op.f('ix_password_reset_codes_code'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index(op.f('ix_loyalty_card_templates_company_id'), table_name='loyalty_card_templates')
    op.drop_table('loyalty_card_templates')
    op.drop_index(op.f('ix_inventory_items_company_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_fee_settings_company_id'), table_name='fee_settings')
    op.drop_table('fee_settings')
    op.drop_index(op.f('ix_company_rewards_company_id'), table_name='company_rewards')
    op.drop_table('company_rewards')
    op.drop_index(op.f('ix_company_point_purchases_plan_id'), table_name='company_point_purchases')
    op.drop_index(op.f('ix_company_point_purchases_company_id'), table_name='company_point_purchases')
    op.drop_index(op.f('ix_company_point_purchases_asaas_id'), table_name='company_point_purchases')
    op.drop_table('company_point_purchases')
    op.drop_index(op.f('ix_company_payments_company_id'), table_name='company_payments')
    op.drop_index(op.f('ix_company_payments_asaas_id'), table_name='company_payments')
    op.drop_table('company_payments')
    op.drop_index(op.f('ix_company_password_reset_codes_company_id'), table_name='company_password_reset_codes')
    op.drop_index(op.f('ix_company_password_reset_codes_code'), table_name='company_password_reset_codes')
    op.drop_table('company_password_reset_codes')
    op.drop_table('company_categories')
    op.drop_table('commission_wallets')
    op.drop_index(op.f('ix_cashback_programs_company_id'), table_name='cashback_programs')
    op.drop_table('cashback_programs')
    op.drop_index(op.f('ix_branches_slug'), table_name='branches')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_table('slide_images')
    op.drop_index(op.f('ix_selection_items_item_id'), table_name='selection_items')
    op.drop_table('selection_items')
    op.drop_index(op.f('ix_reward_products_active'), table_name='reward_products')
    op.drop_table('reward_products')
    op.drop_table('reward_categories')
    op.drop_table('point_plans')
    op.drop_index(op.f('ix_phone_verifications_phone'), table_name='phone_verifications')
    op.drop_index(op.f('ix_phone_verifications_code'), table_name='phone_verifications')
    op.drop_table('phone_verifications')
    op.drop_index(op.f('ix_milestones_points'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_companies_location'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_customer_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
