"""add limits to cashback_programs

Revision ID: 32e43706cd73
Revises: 00942ce174de
Create Date: 2025-06-13 23:00:22.722977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e43706cd73'
down_revision: Union[str, None] = '00942ce174de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashback_programs', sa.Column('max_per_user', sa.Integer(), nullable=True))
    op.add_column('cashback_programs', sa.Column('min_cashback_per_user', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashback_programs', 'min_cashback_per_user')
    op.drop_column('cashback_programs', 'max_per_user')
    # ### end Alembic commands ###
