"""create points rule and wallet

Revision ID: 349b277d8722
Revises: 5e4e5b833766
Create Date: 2025-07-01 20:28:06.581315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '349b277d8722'
down_revision: Union[str, None] = '5e4e5b833766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Enum('value_spent', 'event', 'frequency', 'category', 'first_purchase', 'recurrence', 'digital_behavior', 'special_date', 'geolocation', 'inventory', name='rule_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_rules_company_id'), 'points_rules', ['company_id'], unique=False)
    op.create_table('user_points_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_wallets_company_id'), 'user_points_wallets', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_points_wallets_user_id'), 'user_points_wallets', ['user_id'], unique=False)
    op.create_table('user_points_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('award', 'adjustment', name='userpointstxtype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['points_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_points_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_points_transactions_company_id'), 'user_points_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_points_transactions_user_id'), 'user_points_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_points_transactions_wallet_id'), 'user_points_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_points_transactions_wallet_id'), table_name='user_points_transactions')
    op.drop_index(op.f('ix_user_points_transactions_user_id'), table_name='user_points_transactions')
    op.drop_index(op.f('ix_user_points_transactions_company_id'), table_name='user_points_transactions')
    op.drop_table('user_points_transactions')
    op.drop_index(op.f('ix_user_points_wallets_user_id'), table_name='user_points_wallets')
    op.drop_index(op.f('ix_user_points_wallets_company_id'), table_name='user_points_wallets')
    op.drop_table('user_points_wallets')
    op.drop_index(op.f('ix_points_rules_company_id'), table_name='points_rules')
    op.drop_table('points_rules')
    # ### end Alembic commands ###
