"""Adiciona número, bairro, complemento, online_url, only_online em Company

Revision ID: 3793de6fd86b
Revises: 8d343c97768e
Create Date: 2025-06-05 19:30:02.507163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3793de6fd86b'
down_revision: Union[str, None] = '8d343c97768e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('number', sa.String(length=20), nullable=False))
    op.add_column('companies', sa.Column('neighborhood', sa.String(length=100), nullable=False))
    op.add_column('companies', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('online_url', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('only_online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'only_online')
    op.drop_column('companies', 'online_url')
    op.drop_column('companies', 'complement')
    op.drop_column('companies', 'neighborhood')
    op.drop_column('companies', 'number')
    # ### end Alembic commands ###
