"""add verification fields

Revision ID: 3a5070fa8fbc
Revises: 32d5f837395c
Create Date: 2025-05-07 12:53:04.281233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5070fa8fbc'
down_revision: Union[str, None] = '32d5f837395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_terms', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('pre_registered', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'pre_registered')
    op.drop_column('users', 'accepted_terms')
    # ### end Alembic commands ###
