"""create user_companies association table

Revision ID: 3c44ab99ae5a
Revises: e531de4b0cf7
Create Date: 2025-05-07 16:12:52.300400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c44ab99ae5a'
down_revision: Union[str, None] = 'e531de4b0cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.drop_index('ix_users_company_id', table_name='users')
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_company_id_fkey', 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_users_company_id', 'users', ['company_id'], unique=False)
    op.drop_table('user_companies')
    # ### end Alembic commands ###
