"""transfer_method modificações

Revision ID: 40cfed6da5c9
Revises: 974f179db2fa
Create Date: 2025-06-27 10:55:26.231707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cfed6da5c9'
down_revision: Union[str, None] = '974f179db2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_withdrawals', sa.Column('transfer_method_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'commission_withdrawals', 'transfer_methods', ['transfer_method_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commission_withdrawals', type_='foreignkey')
    op.drop_column('commission_withdrawals', 'transfer_method_id')
    # ### end Alembic commands ###
