"""modificoes

Revision ID: 5495a41cbed8
Revises: 35ab6780a515
Create Date: 2025-07-03 17:37:28.354180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5495a41cbed8'
down_revision: Union[str, None] = '35ab6780a515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_points_wallets_company_id', table_name='user_points_wallets')
    op.drop_constraint('user_points_wallets_company_id_fkey', 'user_points_wallets', type_='foreignkey')
    op.drop_column('user_points_wallets', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_points_wallets', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_points_wallets_company_id_fkey', 'user_points_wallets', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_points_wallets_company_id', 'user_points_wallets', ['company_id'], unique=False)
    # ### end Alembic commands ###
