"""add wallet_transactions with FKs to user_cashback_wallets

Revision ID: 56ea143d0c9f
Revises: cc3dd031ef1b
Create Date: 2025-06-25 10:42:25.860817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56ea143d0c9f'
down_revision: Union[str, None] = 'cc3dd031ef1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'company_id'], ['user_cashback_wallets.user_id', 'user_cashback_wallets.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_cashback_wallet_transactions_company_id', table_name='user_cashback_wallet_transactions')
    op.drop_index('ix_user_cashback_wallet_transactions_user_id', table_name='user_cashback_wallet_transactions')
    op.drop_table('user_cashback_wallet_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cashback_wallet_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('credit', 'debit', name='transaction_type'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='user_cashback_wallet_transactions_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_cashback_wallet_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_cashback_wallet_transactions_pkey')
    )
    op.create_index('ix_user_cashback_wallet_transactions_user_id', 'user_cashback_wallet_transactions', ['user_id'], unique=False)
    op.create_index('ix_user_cashback_wallet_transactions_company_id', 'user_cashback_wallet_transactions', ['company_id'], unique=False)
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
