"""create credits_wallet_transactions

Revision ID: 5e4e5b833766
Revises: b7ad18f36d53
Create Date: 2025-07-01 14:16:47.078120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4e5b833766'
down_revision: Union[str, None] = 'b7ad18f36d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits_wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='credittxtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_wallet_transactions_company_id'), 'credits_wallet_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_credits_wallet_transactions_wallet_id'), 'credits_wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credits_wallet_transactions_wallet_id'), table_name='credits_wallet_transactions')
    op.drop_index(op.f('ix_credits_wallet_transactions_company_id'), table_name='credits_wallet_transactions')
    op.drop_table('credits_wallet_transactions')
    # ### end Alembic commands ###
