"""add customer_id to companies

Revision ID: 60088e25fd3c
Revises: fd0416161aea
Create Date: 2025-06-16 13:49:54.417741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60088e25fd3c'
down_revision: Union[str, None] = 'fd0416161aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_companies_customer_id'), 'companies', ['customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_customer_id'), table_name='companies')
    op.drop_column('companies', 'customer_id')
    # ### end Alembic commands ###
