"""create selection_items table

Revision ID: 6324f0d3e1e1
Revises: a2cd11b328b0
Create Date: 2025-07-10 21:03:29.779660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6324f0d3e1e1'
down_revision: Union[str, None] = 'a2cd11b328b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selection_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('product', 'category', name='selection_type'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'item_id', name='uq_selection_type_item')
    )
    op.create_index(op.f('ix_selection_items_item_id'), 'selection_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selection_items_item_id'), table_name='selection_items')
    op.drop_table('selection_items')
    # ### end Alembic commands ###
