"""create fee_settings table

Revision ID: 64301a6bfb98
Revises: 56ea143d0c9f
Create Date: 2025-06-26 11:51:27.042111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64301a6bfb98'
down_revision: Union[str, None] = '56ea143d0c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('setting_type', sa.Enum('cashback', 'points', 'loyalty', name='settingtypeenum'), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'setting_type', name='uq_fee_company_type')
    )
    op.create_index(op.f('ix_fee_settings_company_id'), 'fee_settings', ['company_id'], unique=False)
    op.create_foreign_key(None, 'wallet_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_fee_settings_company_id'), table_name='fee_settings')
    op.drop_table('fee_settings')
    # ### end Alembic commands ###
