"""Adiciona cpf a User e campos extras em Address

Revision ID: 8d343c97768e
Revises: 76407b637d67
Create Date: 2025-06-05 18:00:31.708918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d343c97768e'
down_revision: Union[str, None] = '76407b637d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_unique_constraint(None, 'users', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
