"""transfer_method

Revision ID: 974f179db2fa
Revises: 6bcff3d22b86
Create Date: 2025-06-27 10:22:40.010740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974f179db2fa'
down_revision: Union[str, None] = '6bcff3d22b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('key_type', sa.Enum('PHONE', 'EMAIL', 'CPF', 'CNPJ', 'RANDOM', name='pixkeytype'), nullable=False),
    sa.Column('key_value', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_methods_user_id'), 'transfer_methods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_methods_user_id'), table_name='transfer_methods')
    op.drop_table('transfer_methods')
    # ### end Alembic commands ###
