"""user points stats

Revision ID: a0d86d358405
Revises: 4ede0ac1c1c3
Create Date: 2025-07-04 20:07:20.004944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0d86d358405'
down_revision: Union[str, None] = '4ede0ac1c1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_points_stats', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('user_points_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_points_stats_user_id'), 'user_points_stats', ['user_id'], unique=True)
    op.create_foreign_key(None, 'user_points_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_points_transactions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_points_transactions', type_='foreignkey')
    op.drop_constraint(None, 'user_points_stats', type_='foreignkey')
    op.drop_index(op.f('ix_user_points_stats_user_id'), table_name='user_points_stats')
    op.alter_column('user_points_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('user_points_stats', 'id')
    # ### end Alembic commands ###
