"""create slide_images table

Revision ID: a2cd11b328b0
Revises: 5978a016911f
Create Date: 2025-07-10 20:18:19.966563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cd11b328b0'
down_revision: Union[str, None] = '5978a016911f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_company_reset_code', table_name='company_password_reset_codes')
    op.alter_column('password_reset_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('password_reset_codes_user_id_fkey', 'password_reset_codes', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_codes', type_='foreignkey')
    op.create_foreign_key('password_reset_codes_user_id_fkey', 'password_reset_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('password_reset_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_company_reset_code', 'company_password_reset_codes', ['code'], unique=False)
    op.drop_table('slide_images')
    # ### end Alembic commands ###
