"""drop cpf column from users

Revision ID: a7441a7c1ee4
Revises: 3a5070fa8fbc
Create Date: 2025-05-07 14:24:32.904560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7441a7c1ee4'
down_revision: Union[str, None] = '3a5070fa8fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_cpf_enc_key', 'users', type_='unique')
    op.drop_column('users', 'cpf_enc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf_enc', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_cpf_enc_key', 'users', ['cpf_enc'])
    # ### end Alembic commands ###
