"""points

Revision ID: b1e71c231e72
Revises: 40cfed6da5c9
Create Date: 2025-06-28 17:27:38.952255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e71c231e72'
down_revision: Union[str, None] = '40cfed6da5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_point_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('asaas_id', sa.String(length=255), nullable=False),
    sa.Column('pix_qr_code', sa.Text(), nullable=True),
    sa.Column('pix_copy_paste_code', sa.Text(), nullable=True),
    sa.Column('pix_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='purchasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['point_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_point_purchases_asaas_id'), 'company_point_purchases', ['asaas_id'], unique=True)
    op.create_index(op.f('ix_company_point_purchases_company_id'), 'company_point_purchases', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_point_purchases_plan_id'), 'company_point_purchases', ['plan_id'], unique=False)
    op.create_table('points_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=0), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_wallets_company_id'), 'points_wallets', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_wallets_company_id'), table_name='points_wallets')
    op.drop_table('points_wallets')
    op.drop_index(op.f('ix_company_point_purchases_plan_id'), table_name='company_point_purchases')
    op.drop_index(op.f('ix_company_point_purchases_company_id'), table_name='company_point_purchases')
    op.drop_index(op.f('ix_company_point_purchases_asaas_id'), table_name='company_point_purchases')
    op.drop_table('company_point_purchases')
    op.drop_table('point_plans')
    # ### end Alembic commands ###
