"""points transactions

Revision ID: b7ad18f36d53
Revises: a43cea17cb6e
Create Date: 2025-07-01 11:51:44.834386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ad18f36d53'
down_revision: Union[str, None] = 'a43cea17cb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['points_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_wallet_transactions_company_id'), 'points_wallet_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_points_wallet_transactions_wallet_id'), 'points_wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_wallet_transactions_wallet_id'), table_name='points_wallet_transactions')
    op.drop_index(op.f('ix_points_wallet_transactions_company_id'), table_name='points_wallet_transactions')
    op.drop_table('points_wallet_transactions')
    # ### end Alembic commands ###
