"""add location geography to companies

Revision ID: c4f5a4d533a1
Revises: d3dd3f538aed
Create Date: 2025-07-16 17:07:31.860065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c4f5a4d533a1'
down_revision: Union[str, None] = 'd3dd3f538aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
