"""add wallet transactions history

Revision ID: cc3dd031ef1b
Revises: 897da4cbb5fb
Create Date: 2025-06-25 10:26:46.879281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3dd031ef1b'
down_revision: Union[str, None] = '897da4cbb5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cashback_wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'debit', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cashback_wallet_transactions_company_id'), 'user_cashback_wallet_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_cashback_wallet_transactions_user_id'), 'user_cashback_wallet_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cashback_wallet_transactions_user_id'), table_name='user_cashback_wallet_transactions')
    op.drop_index(op.f('ix_user_cashback_wallet_transactions_company_id'), table_name='user_cashback_wallet_transactions')
    op.drop_table('user_cashback_wallet_transactions')
    # ### end Alembic commands ###
