"""create cashback program and cashbacks

Revision ID: fa0cd2dac3e7
Revises: 7d00fdf7c77f
Create Date: 2025-06-10 16:41:44.526955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa0cd2dac3e7'
down_revision: Union[str, None] = '7d00fdf7c77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referrals_company_id', table_name='referrals')
    op.drop_index('ix_referrals_user_id', table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='referrals_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='referrals_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_referrals_user_company')
    )
    op.create_index('ix_referrals_user_id', 'referrals', ['user_id'], unique=False)
    op.create_index('ix_referrals_company_id', 'referrals', ['company_id'], unique=False)
    # ### end Alembic commands ###
